imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: @SyliusCoreBundle/Resources/config/app/main.yml }

framework:
    translator:      { fallback: %sylius.locale% }
    secret:          %sylius.secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: %kernel.debug%
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] }
    default_locale:  "%sylius.locale%"
    trusted_proxies: ~
    session:         ~

twig:
    form:
        resources:
            - 'SyliusWebBundle::forms.html.twig'
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

assetic:
    debug:          %kernel.debug%
    use_controller: false
    bundles:        ['SyliusWebBundle']
    filters:
        cssrewrite: ~

doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                driver:   %sylius.database.driver%
                host:     %sylius.database.host%
                port:     %sylius.database.port%
                dbname:   %sylius.database.name%
                user:     %sylius.database.user%
                password: %sylius.database.password%
                charset:  UTF8
            legacy:
                driver:   "%legacy_database_driver%"
                host:     "%legacy_database_host%"
                port:     "%legacy_database_port%"
                dbname:   "%legacy_database_name%"
                user:     "%legacy_database_user%"
                password: "%legacy_database_password%"
                charset:  UTF8
    orm:
        auto_generate_proxy_classes: %kernel.debug%
        entity_managers:
            default:
                connection: default
                mappings:
                    gedmo_loggable:
                        type: annotation
                        prefix: Gedmo\Loggable\Entity
                        dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Loggable/Entity"
                        is_bundle: false
                    WunSharedDomainModelsBundle:
                        type: yml
                        dir: ../DomainModelsOrmBundle/Resources/config/doctrine
                filters:
                    softdeleteable:
                        class: Gedmo\SoftDeleteable\Filter\SoftDeleteableFilter
                        enabled: true
            legacy:
                connection: legacy
                mappings:
                    WunIrisLegacyBundle: ~

doctrine_phpcr:
    session:
        backend:
            type: doctrinedbal
        workspace: default
        username: admin
        password: admin
    odm:
        auto_mapping: true

doctrine_migrations:
    dir_name: %kernel.root_dir%/migrations
    namespace: Sylius\Migrations
    table_name: sylius_migrations
    name: Sylius Migrations

swiftmailer:
    transport: %sylius.mailer.transport%
    host:      %sylius.mailer.host%
    username:  %sylius.mailer.user%
    password:  %sylius.mailer.password%
    spool:     { type: memory }
