imports:
    - { resource: config.yml }

framework:
    test: ~
    default_locale:  "en"
    router:   { resource: "%kernel.root_dir%/config/routing_dev.yml" }
    profiler: { only_exceptions: false }
    session:
        storage_id: session.storage.mock_file

web_profiler:
    toolbar: true
    intercept_redirects: false

swiftmailer:
    disable_delivery: true

doctrine:
    dbal:
        dbname:   %sylius.database.name%_test
        driver_class: Sylius\Bundle\CoreBundle\Tests\MySqlDriver

sylius_money:
    currency: EUR
    locale: en_US

sylius_payment:
    gateways:
        cc:     Credit Card
        test:   Test
        stripe: Stripe

doctrine_cache:
    providers:
        sylius_settings:
            type: array

monolog:
    handlers:
        main:
            type:  stream
            path:  %kernel.logs_dir%/%kernel.environment%.log
            level: debug
        firephp:
            type:  firephp
            level: info
