<?php

namespace Sylius\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration;
use Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
class Version20140506220636 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql", "Migration can only be executed safely on 'mysql'.");
        
        $this->addSql("CREATE TABLE mbr_accountType (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(125) NOT NULL, UNIQUE INDEX mbr_accountType_name_unique (name), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE mbr_address (id INT AUTO_INCREMENT NOT NULL, country_id INT DEFAULT NULL, region_id INT DEFAULT NULL, postcode VARCHAR(20) DEFAULT NULL, city VARCHAR(125) DEFAULT NULL, street1 VARCHAR(255) DEFAULT NULL, street2 VARCHAR(255) DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, deleted_at DATETIME DEFAULT NULL, INDEX IDX_E7A40458F92F3E70 (country_id), INDEX IDX_E7A4045898260155 (region_id), INDEX mbr_address_postcode_idx (postcode), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE mbr_addressAddressTypeLink (address_id INT NOT NULL, address_type_id INT NOT NULL, INDEX IDX_30E0CA44F5B7AF75 (address_id), INDEX IDX_30E0CA449EA97B0B (address_type_id), PRIMARY KEY(address_id, address_type_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE mbr_addressOptinTypeLink (address_id INT NOT NULL, optin_type_id INT NOT NULL, INDEX IDX_C7C8A35FF5B7AF75 (address_id), INDEX IDX_C7C8A35F21332E67 (optin_type_id), PRIMARY KEY(address_id, optin_type_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE mbr_addressOptinAudit (id INT AUTO_INCREMENT NOT NULL, address_id INT DEFAULT NULL, optin_type_id INT DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, deleted_at DATETIME DEFAULT NULL, INDEX IDX_F286CEC7F5B7AF75 (address_id), INDEX IDX_F286CEC721332E67 (optin_type_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE mbr_addressType (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(125) NOT NULL, UNIQUE INDEX mbr_addressType_name_unique (name), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE mbr_business (id INT AUTO_INCREMENT NOT NULL, tax_number VARCHAR(40) DEFAULT NULL, name VARCHAR(125) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, deleted_at DATETIME DEFAULT NULL, INDEX mbr_business_name_idx (name), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE mbr_businessAddressLink (business_id INT NOT NULL, address_id INT NOT NULL, INDEX IDX_88F78A72A89DB457 (business_id), INDEX IDX_88F78A72F5B7AF75 (address_id), PRIMARY KEY(business_id, address_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE mbr_businessEmailLink (business_id INT NOT NULL, email_id INT NOT NULL, INDEX IDX_3EC2BD2CA89DB457 (business_id), INDEX IDX_3EC2BD2CA832C1C9 (email_id), PRIMARY KEY(business_id, email_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE mbr_businessPhoneLink (business_id INT NOT NULL, phone_id INT NOT NULL, INDEX IDX_D05F9DE2A89DB457 (business_id), INDEX IDX_D05F9DE23B7323CB (phone_id), PRIMARY KEY(business_id, phone_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE mbr_contact (id INT AUTO_INCREMENT NOT NULL, language_id INT DEFAULT NULL, salutation VARCHAR(20) DEFAULT NULL, date_of_birth DATE DEFAULT NULL, tax_number VARCHAR(40) DEFAULT NULL, first_name VARCHAR(80) NOT NULL, last_name VARCHAR(80) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, deleted_at DATETIME DEFAULT NULL, INDEX IDX_A6888DE182F1BAF4 (language_id), INDEX mbr_contact_lastName_idx (last_name), INDEX mbr_contact_firstName1_idx (first_name, last_name), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE mbr_contactBusinessLink (contact_id INT NOT NULL, business_id INT NOT NULL, INDEX IDX_509E4031E7A1254A (contact_id), UNIQUE INDEX UNIQ_509E4031A89DB457 (business_id), PRIMARY KEY(contact_id, business_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE mbr_contactAddressLink (contact_id INT NOT NULL, address_id INT NOT NULL, INDEX IDX_52C848E7E7A1254A (contact_id), INDEX IDX_52C848E7F5B7AF75 (address_id), PRIMARY KEY(contact_id, address_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE mbr_contactEmailLink (contact_id INT NOT NULL, email_id INT NOT NULL, INDEX IDX_410FDE15E7A1254A (contact_id), INDEX IDX_410FDE15A832C1C9 (email_id), PRIMARY KEY(contact_id, email_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE mbr_contactPhoneLink (contact_id INT NOT NULL, phone_id INT NOT NULL, INDEX IDX_AF92FEDBE7A1254A (contact_id), INDEX IDX_AF92FEDB3B7323CB (phone_id), PRIMARY KEY(contact_id, phone_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE mbr_contactContactTypeLink (contact_id INT NOT NULL, contact_type_id INT NOT NULL, INDEX IDX_AA5F436BE7A1254A (contact_id), INDEX IDX_AA5F436B5F63AD12 (contact_type_id), PRIMARY KEY(contact_id, contact_type_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE mbr_contactType (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(125) NOT NULL, UNIQUE INDEX mbr_contactType_name_unique (name), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE mbr_country (id INT AUTO_INCREMENT NOT NULL, tax_rate_id INT DEFAULT NULL, iso_code_id INT DEFAULT NULL, name VARCHAR(125) NOT NULL, image_link VARCHAR(255) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, deleted_at DATETIME DEFAULT NULL, INDEX IDX_B999A2BFFDD13F95 (tax_rate_id), INDEX IDX_B999A2BFE80AA9BC (iso_code_id), UNIQUE INDEX mbr_country_name_unique (name), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE mbr_email (id INT AUTO_INCREMENT NOT NULL, email VARCHAR(125) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, deleted_at DATETIME DEFAULT NULL, UNIQUE INDEX mbr_email_email_unique (email), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE mbr_emailEmailTypeLink (email_id INT NOT NULL, email_type_id INT NOT NULL, INDEX IDX_B537F65AA832C1C9 (email_id), INDEX IDX_B537F65A788CE45C (email_type_id), PRIMARY KEY(email_id, email_type_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE mbr_emailOptinTypeLink (email_id INT NOT NULL, optin_type_id INT NOT NULL, INDEX IDX_EC883C61A832C1C9 (email_id), INDEX IDX_EC883C6121332E67 (optin_type_id), PRIMARY KEY(email_id, optin_type_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE mbr_emailOptinAudit (id INT AUTO_INCREMENT NOT NULL, email_id INT DEFAULT NULL, optin_type_id INT DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, deleted_at DATETIME DEFAULT NULL, INDEX IDX_EA66841CA832C1C9 (email_id), INDEX IDX_EA66841C21332E67 (optin_type_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE mbr_emailType (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(125) NOT NULL, UNIQUE INDEX mbr_emailType_name_unique (name), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE mbr_emailValidate (id INT AUTO_INCREMENT NOT NULL, email_id INT DEFAULT NULL, validate_ip INT NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, deleted_at DATETIME DEFAULT NULL, UNIQUE INDEX UNIQ_B4882621A832C1C9 (email_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE mbr_flagType (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(125) NOT NULL, UNIQUE INDEX mbr_flagType_name_unique (name), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE mbr_isoCode (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(5) NOT NULL, UNIQUE INDEX mbr_isoCode_name_unique (name), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE mbr_language (id INT AUTO_INCREMENT NOT NULL, iso_code_id INT DEFAULT NULL, name VARCHAR(125) NOT NULL, image_link VARCHAR(255) NOT NULL, INDEX IDX_2B3EF1AEE80AA9BC (iso_code_id), UNIQUE INDEX mbr_language_name_unique (name), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE mbr_member (id INT AUTO_INCREMENT NOT NULL, account_type_id INT DEFAULT NULL, original_enroller_id INT DEFAULT NULL, highest_rank_id INT DEFAULT NULL, status_type_id INT DEFAULT NULL, balance NUMERIC(12, 2) NOT NULL, enroll_ip INT UNSIGNED NOT NULL, username VARCHAR(80) NOT NULL, password VARCHAR(125) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, deleted_at DATETIME DEFAULT NULL, INDEX IDX_4FC81AFCC6798DB (account_type_id), INDEX IDX_4FC81AFC9F7F6383 (original_enroller_id), INDEX IDX_4FC81AFCD3FFF3B9 (highest_rank_id), INDEX IDX_4FC81AFCCD9CFB16 (status_type_id), UNIQUE INDEX mbr_member_username_unique (username), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE mbr_memberContactLink (member_id INT NOT NULL, contact_id INT NOT NULL, INDEX IDX_E0A454417597D3FE (member_id), UNIQUE INDEX UNIQ_E0A45441E7A1254A (contact_id), PRIMARY KEY(member_id, contact_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE mbr_memberFlagTypeLink (member_id INT NOT NULL, flag_type_id INT NOT NULL, INDEX IDX_DA499A117597D3FE (member_id), INDEX IDX_DA499A1134753ADC (flag_type_id), PRIMARY KEY(member_id, flag_type_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE mbr_memberFlagAudit (id INT AUTO_INCREMENT NOT NULL, flag_type_id INT DEFAULT NULL, member_id INT DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, deleted_at DATETIME DEFAULT NULL, INDEX IDX_FD4BF03C34753ADC (flag_type_id), INDEX IDX_FD4BF03C7597D3FE (member_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE mbr_memberLoginAudit (id INT AUTO_INCREMENT NOT NULL, member_id INT DEFAULT NULL, ip_address INT NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, deleted_at DATETIME DEFAULT NULL, INDEX IDX_AF4DD5197597D3FE (member_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE mbr_memberMeta (id INT AUTO_INCREMENT NOT NULL, member_id INT DEFAULT NULL, meta_type_id INT DEFAULT NULL, value VARCHAR(255) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, deleted_at DATETIME DEFAULT NULL, INDEX IDX_4F8135F57597D3FE (member_id), INDEX IDX_4F8135F58C379371 (meta_type_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE mbr_memberSite (id INT AUTO_INCREMENT NOT NULL, member_id INT DEFAULT NULL, phone_id INT DEFAULT NULL, email_id INT DEFAULT NULL, avatar_url VARCHAR(125) DEFAULT NULL, name VARCHAR(125) NOT NULL, about VARCHAR(255) DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, deleted_at DATETIME DEFAULT NULL, UNIQUE INDEX UNIQ_F13028247597D3FE (member_id), INDEX IDX_F13028243B7323CB (phone_id), INDEX IDX_F1302824A832C1C9 (email_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE mbr_memberSiteSocialMediaLink (member_site_id INT NOT NULL, social_media_id INT NOT NULL, INDEX IDX_1EB442FE4949A1D2 (member_site_id), INDEX IDX_1EB442FE64AE4959 (social_media_id), PRIMARY KEY(member_site_id, social_media_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE mbr_memberStatusTypeAudit (id INT AUTO_INCREMENT NOT NULL, member_id INT DEFAULT NULL, status_type_id INT DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, deleted_at DATETIME DEFAULT NULL, INDEX IDX_DC6511BF7597D3FE (member_id), INDEX IDX_DC6511BFCD9CFB16 (status_type_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE mbr_metaType (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(125) NOT NULL, UNIQUE INDEX mbr_metaType_name_unique (name), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE mbr_optinType (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(125) NOT NULL, UNIQUE INDEX mbr_optinType_name_unique (name), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE mbr_phone (id INT AUTO_INCREMENT NOT NULL, phone VARCHAR(40) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, deleted_at DATETIME DEFAULT NULL, INDEX mbr_phone_phone_idx (phone), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE mbr_phonePhoneTypeLink (phone_id INT NOT NULL, phone_type_id INT NOT NULL, INDEX IDX_B397C5253B7323CB (phone_id), INDEX IDX_B397C525550E00A1 (phone_type_id), PRIMARY KEY(phone_id, phone_type_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE mbr_phoneOptinTypeLink (phone_id INT NOT NULL, optin_type_id INT NOT NULL, INDEX IDX_C7AAEBE33B7323CB (phone_id), INDEX IDX_C7AAEBE321332E67 (optin_type_id), PRIMARY KEY(phone_id, optin_type_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE mbr_phoneOptinAudit (id INT AUTO_INCREMENT NOT NULL, phone_id INT DEFAULT NULL, optin_type_id INT DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, deleted_at DATETIME DEFAULT NULL, INDEX IDX_EC13100F3B7323CB (phone_id), INDEX IDX_EC13100F21332E67 (optin_type_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE mbr_phoneType (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(125) NOT NULL, UNIQUE INDEX mbr_phoneType_name_unique (name), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE com_rank (id INT AUTO_INCREMENT NOT NULL, parent_id INT DEFAULT NULL, name VARCHAR(125) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, deleted_at DATETIME DEFAULT NULL, UNIQUE INDEX UNIQ_E1AC375A727ACA70 (parent_id), INDEX mbr_rank_name_idx (name), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE com_rankMeta (id INT AUTO_INCREMENT NOT NULL, rank_id INT DEFAULT NULL, value VARCHAR(255) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, deleted_at DATETIME DEFAULT NULL, INDEX IDX_27EB86D37616678F (rank_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE com_rankRequirement (id INT AUTO_INCREMENT NOT NULL, rank_id INT DEFAULT NULL, rank_requirement_type_id INT DEFAULT NULL, value VARCHAR(255) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, deleted_at DATETIME DEFAULT NULL, INDEX IDX_7792617616678F (rank_id), INDEX IDX_779261180EBDEC (rank_requirement_type_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE com_rankRequirementType (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(125) NOT NULL, UNIQUE INDEX mbr_rankRequirementType_name_unique (name), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE com_rankReward (id INT AUTO_INCREMENT NOT NULL, rank_id INT DEFAULT NULL, rank_reward_type_id INT DEFAULT NULL, value VARCHAR(255) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, deleted_at DATETIME DEFAULT NULL, INDEX IDX_58F424487616678F (rank_id), INDEX IDX_58F42448ABE136B8 (rank_reward_type_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE com_rankRewardType (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(125) NOT NULL, UNIQUE INDEX mbr_rankRewardType_name_unique (name), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE mbr_region (id INT AUTO_INCREMENT NOT NULL, iso_code_id INT DEFAULT NULL, tax_rate_id INT DEFAULT NULL, country_id INT DEFAULT NULL, name VARCHAR(125) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, deleted_at DATETIME DEFAULT NULL, INDEX IDX_304E11F2E80AA9BC (iso_code_id), INDEX IDX_304E11F2FDD13F95 (tax_rate_id), INDEX IDX_304E11F2F92F3E70 (country_id), INDEX mbr_region_name_idx (name), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE mbr_socialMedia (id INT AUTO_INCREMENT NOT NULL, social_media_type_id INT DEFAULT NULL, url VARCHAR(255) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, deleted_at DATETIME DEFAULT NULL, INDEX IDX_4249EFA51221844E (social_media_type_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE mbr_socialMediaType (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(125) NOT NULL, UNIQUE INDEX mbr_socialMediaType_name_unique (name), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE mbr_statusType (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(125) NOT NULL, UNIQUE INDEX mbr_statusType_name_unique (name), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE mbr_taxRate (id INT AUTO_INCREMENT NOT NULL, percent NUMERIC(4, 2) NOT NULL, UNIQUE INDEX mbr_taxRate_percent_unique (percent), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE sylius_price_wun_account_type (price_id INT NOT NULL, account_type_id INT NOT NULL, INDEX IDX_B29E656FD614C7E7 (price_id), INDEX IDX_B29E656FC6798DB (account_type_id), PRIMARY KEY(price_id, account_type_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("ALTER TABLE mbr_address ADD CONSTRAINT FK_E7A40458F92F3E70 FOREIGN KEY (country_id) REFERENCES mbr_country (id)");
        $this->addSql("ALTER TABLE mbr_address ADD CONSTRAINT FK_E7A4045898260155 FOREIGN KEY (region_id) REFERENCES mbr_region (id)");
        $this->addSql("ALTER TABLE mbr_addressAddressTypeLink ADD CONSTRAINT FK_30E0CA44F5B7AF75 FOREIGN KEY (address_id) REFERENCES mbr_address (id)");
        $this->addSql("ALTER TABLE mbr_addressAddressTypeLink ADD CONSTRAINT FK_30E0CA449EA97B0B FOREIGN KEY (address_type_id) REFERENCES mbr_addressType (id)");
        $this->addSql("ALTER TABLE mbr_addressOptinTypeLink ADD CONSTRAINT FK_C7C8A35FF5B7AF75 FOREIGN KEY (address_id) REFERENCES mbr_address (id)");
        $this->addSql("ALTER TABLE mbr_addressOptinTypeLink ADD CONSTRAINT FK_C7C8A35F21332E67 FOREIGN KEY (optin_type_id) REFERENCES mbr_optinType (id)");
        $this->addSql("ALTER TABLE mbr_addressOptinAudit ADD CONSTRAINT FK_F286CEC7F5B7AF75 FOREIGN KEY (address_id) REFERENCES mbr_address (id)");
        $this->addSql("ALTER TABLE mbr_addressOptinAudit ADD CONSTRAINT FK_F286CEC721332E67 FOREIGN KEY (optin_type_id) REFERENCES mbr_optinType (id)");
        $this->addSql("ALTER TABLE mbr_businessAddressLink ADD CONSTRAINT FK_88F78A72A89DB457 FOREIGN KEY (business_id) REFERENCES mbr_business (id)");
        $this->addSql("ALTER TABLE mbr_businessAddressLink ADD CONSTRAINT FK_88F78A72F5B7AF75 FOREIGN KEY (address_id) REFERENCES mbr_address (id)");
        $this->addSql("ALTER TABLE mbr_businessEmailLink ADD CONSTRAINT FK_3EC2BD2CA89DB457 FOREIGN KEY (business_id) REFERENCES mbr_business (id)");
        $this->addSql("ALTER TABLE mbr_businessEmailLink ADD CONSTRAINT FK_3EC2BD2CA832C1C9 FOREIGN KEY (email_id) REFERENCES mbr_email (id)");
        $this->addSql("ALTER TABLE mbr_businessPhoneLink ADD CONSTRAINT FK_D05F9DE2A89DB457 FOREIGN KEY (business_id) REFERENCES mbr_business (id)");
        $this->addSql("ALTER TABLE mbr_businessPhoneLink ADD CONSTRAINT FK_D05F9DE23B7323CB FOREIGN KEY (phone_id) REFERENCES mbr_phone (id)");
        $this->addSql("ALTER TABLE mbr_contact ADD CONSTRAINT FK_A6888DE182F1BAF4 FOREIGN KEY (language_id) REFERENCES mbr_language (id)");
        $this->addSql("ALTER TABLE mbr_contactBusinessLink ADD CONSTRAINT FK_509E4031E7A1254A FOREIGN KEY (contact_id) REFERENCES mbr_contact (id)");
        $this->addSql("ALTER TABLE mbr_contactBusinessLink ADD CONSTRAINT FK_509E4031A89DB457 FOREIGN KEY (business_id) REFERENCES mbr_business (id)");
        $this->addSql("ALTER TABLE mbr_contactAddressLink ADD CONSTRAINT FK_52C848E7E7A1254A FOREIGN KEY (contact_id) REFERENCES mbr_contact (id)");
        $this->addSql("ALTER TABLE mbr_contactAddressLink ADD CONSTRAINT FK_52C848E7F5B7AF75 FOREIGN KEY (address_id) REFERENCES mbr_address (id)");
        $this->addSql("ALTER TABLE mbr_contactEmailLink ADD CONSTRAINT FK_410FDE15E7A1254A FOREIGN KEY (contact_id) REFERENCES mbr_contact (id)");
        $this->addSql("ALTER TABLE mbr_contactEmailLink ADD CONSTRAINT FK_410FDE15A832C1C9 FOREIGN KEY (email_id) REFERENCES mbr_email (id)");
        $this->addSql("ALTER TABLE mbr_contactPhoneLink ADD CONSTRAINT FK_AF92FEDBE7A1254A FOREIGN KEY (contact_id) REFERENCES mbr_contact (id)");
        $this->addSql("ALTER TABLE mbr_contactPhoneLink ADD CONSTRAINT FK_AF92FEDB3B7323CB FOREIGN KEY (phone_id) REFERENCES mbr_phone (id)");
        $this->addSql("ALTER TABLE mbr_contactContactTypeLink ADD CONSTRAINT FK_AA5F436BE7A1254A FOREIGN KEY (contact_id) REFERENCES mbr_contact (id)");
        $this->addSql("ALTER TABLE mbr_contactContactTypeLink ADD CONSTRAINT FK_AA5F436B5F63AD12 FOREIGN KEY (contact_type_id) REFERENCES mbr_contactType (id)");
        $this->addSql("ALTER TABLE mbr_country ADD CONSTRAINT FK_B999A2BFFDD13F95 FOREIGN KEY (tax_rate_id) REFERENCES mbr_taxRate (id)");
        $this->addSql("ALTER TABLE mbr_country ADD CONSTRAINT FK_B999A2BFE80AA9BC FOREIGN KEY (iso_code_id) REFERENCES mbr_isoCode (id)");
        $this->addSql("ALTER TABLE mbr_emailEmailTypeLink ADD CONSTRAINT FK_B537F65AA832C1C9 FOREIGN KEY (email_id) REFERENCES mbr_email (id)");
        $this->addSql("ALTER TABLE mbr_emailEmailTypeLink ADD CONSTRAINT FK_B537F65A788CE45C FOREIGN KEY (email_type_id) REFERENCES mbr_emailType (id)");
        $this->addSql("ALTER TABLE mbr_emailOptinTypeLink ADD CONSTRAINT FK_EC883C61A832C1C9 FOREIGN KEY (email_id) REFERENCES mbr_email (id)");
        $this->addSql("ALTER TABLE mbr_emailOptinTypeLink ADD CONSTRAINT FK_EC883C6121332E67 FOREIGN KEY (optin_type_id) REFERENCES mbr_optinType (id)");
        $this->addSql("ALTER TABLE mbr_emailOptinAudit ADD CONSTRAINT FK_EA66841CA832C1C9 FOREIGN KEY (email_id) REFERENCES mbr_email (id)");
        $this->addSql("ALTER TABLE mbr_emailOptinAudit ADD CONSTRAINT FK_EA66841C21332E67 FOREIGN KEY (optin_type_id) REFERENCES mbr_optinType (id)");
        $this->addSql("ALTER TABLE mbr_emailValidate ADD CONSTRAINT FK_B4882621A832C1C9 FOREIGN KEY (email_id) REFERENCES mbr_email (id)");
        $this->addSql("ALTER TABLE mbr_language ADD CONSTRAINT FK_2B3EF1AEE80AA9BC FOREIGN KEY (iso_code_id) REFERENCES mbr_isoCode (id)");
        $this->addSql("ALTER TABLE mbr_member ADD CONSTRAINT FK_4FC81AFCC6798DB FOREIGN KEY (account_type_id) REFERENCES mbr_accountType (id)");
        $this->addSql("ALTER TABLE mbr_member ADD CONSTRAINT FK_4FC81AFC9F7F6383 FOREIGN KEY (original_enroller_id) REFERENCES mbr_member (id)");
        $this->addSql("ALTER TABLE mbr_member ADD CONSTRAINT FK_4FC81AFCD3FFF3B9 FOREIGN KEY (highest_rank_id) REFERENCES com_rank (id)");
        $this->addSql("ALTER TABLE mbr_member ADD CONSTRAINT FK_4FC81AFCCD9CFB16 FOREIGN KEY (status_type_id) REFERENCES mbr_statusType (id)");
        $this->addSql("ALTER TABLE mbr_memberContactLink ADD CONSTRAINT FK_E0A454417597D3FE FOREIGN KEY (member_id) REFERENCES mbr_member (id)");
        $this->addSql("ALTER TABLE mbr_memberContactLink ADD CONSTRAINT FK_E0A45441E7A1254A FOREIGN KEY (contact_id) REFERENCES mbr_contact (id)");
        $this->addSql("ALTER TABLE mbr_memberFlagTypeLink ADD CONSTRAINT FK_DA499A117597D3FE FOREIGN KEY (member_id) REFERENCES mbr_member (id)");
        $this->addSql("ALTER TABLE mbr_memberFlagTypeLink ADD CONSTRAINT FK_DA499A1134753ADC FOREIGN KEY (flag_type_id) REFERENCES mbr_flagType (id)");
        $this->addSql("ALTER TABLE mbr_memberFlagAudit ADD CONSTRAINT FK_FD4BF03C34753ADC FOREIGN KEY (flag_type_id) REFERENCES mbr_flagType (id)");
        $this->addSql("ALTER TABLE mbr_memberFlagAudit ADD CONSTRAINT FK_FD4BF03C7597D3FE FOREIGN KEY (member_id) REFERENCES mbr_member (id)");
        $this->addSql("ALTER TABLE mbr_memberLoginAudit ADD CONSTRAINT FK_AF4DD5197597D3FE FOREIGN KEY (member_id) REFERENCES mbr_member (id)");
        $this->addSql("ALTER TABLE mbr_memberMeta ADD CONSTRAINT FK_4F8135F57597D3FE FOREIGN KEY (member_id) REFERENCES mbr_member (id)");
        $this->addSql("ALTER TABLE mbr_memberMeta ADD CONSTRAINT FK_4F8135F58C379371 FOREIGN KEY (meta_type_id) REFERENCES mbr_metaType (id)");
        $this->addSql("ALTER TABLE mbr_memberSite ADD CONSTRAINT FK_F13028247597D3FE FOREIGN KEY (member_id) REFERENCES mbr_member (id)");
        $this->addSql("ALTER TABLE mbr_memberSite ADD CONSTRAINT FK_F13028243B7323CB FOREIGN KEY (phone_id) REFERENCES mbr_phone (id)");
        $this->addSql("ALTER TABLE mbr_memberSite ADD CONSTRAINT FK_F1302824A832C1C9 FOREIGN KEY (email_id) REFERENCES mbr_email (id)");
        $this->addSql("ALTER TABLE mbr_memberSiteSocialMediaLink ADD CONSTRAINT FK_1EB442FE4949A1D2 FOREIGN KEY (member_site_id) REFERENCES mbr_memberSite (id)");
        $this->addSql("ALTER TABLE mbr_memberSiteSocialMediaLink ADD CONSTRAINT FK_1EB442FE64AE4959 FOREIGN KEY (social_media_id) REFERENCES mbr_socialMedia (id)");
        $this->addSql("ALTER TABLE mbr_memberStatusTypeAudit ADD CONSTRAINT FK_DC6511BF7597D3FE FOREIGN KEY (member_id) REFERENCES mbr_member (id)");
        $this->addSql("ALTER TABLE mbr_memberStatusTypeAudit ADD CONSTRAINT FK_DC6511BFCD9CFB16 FOREIGN KEY (status_type_id) REFERENCES mbr_statusType (id)");
        $this->addSql("ALTER TABLE mbr_phonePhoneTypeLink ADD CONSTRAINT FK_B397C5253B7323CB FOREIGN KEY (phone_id) REFERENCES mbr_phone (id)");
        $this->addSql("ALTER TABLE mbr_phonePhoneTypeLink ADD CONSTRAINT FK_B397C525550E00A1 FOREIGN KEY (phone_type_id) REFERENCES mbr_phoneType (id)");
        $this->addSql("ALTER TABLE mbr_phoneOptinTypeLink ADD CONSTRAINT FK_C7AAEBE33B7323CB FOREIGN KEY (phone_id) REFERENCES mbr_phone (id)");
        $this->addSql("ALTER TABLE mbr_phoneOptinTypeLink ADD CONSTRAINT FK_C7AAEBE321332E67 FOREIGN KEY (optin_type_id) REFERENCES mbr_optinType (id)");
        $this->addSql("ALTER TABLE mbr_phoneOptinAudit ADD CONSTRAINT FK_EC13100F3B7323CB FOREIGN KEY (phone_id) REFERENCES mbr_phone (id)");
        $this->addSql("ALTER TABLE mbr_phoneOptinAudit ADD CONSTRAINT FK_EC13100F21332E67 FOREIGN KEY (optin_type_id) REFERENCES mbr_optinType (id)");
        $this->addSql("ALTER TABLE com_rank ADD CONSTRAINT FK_E1AC375A727ACA70 FOREIGN KEY (parent_id) REFERENCES com_rank (id)");
        $this->addSql("ALTER TABLE com_rankMeta ADD CONSTRAINT FK_27EB86D37616678F FOREIGN KEY (rank_id) REFERENCES com_rank (id)");
        $this->addSql("ALTER TABLE com_rankRequirement ADD CONSTRAINT FK_7792617616678F FOREIGN KEY (rank_id) REFERENCES com_rank (id)");
        $this->addSql("ALTER TABLE com_rankRequirement ADD CONSTRAINT FK_779261180EBDEC FOREIGN KEY (rank_requirement_type_id) REFERENCES com_rankRequirementType (id)");
        $this->addSql("ALTER TABLE com_rankReward ADD CONSTRAINT FK_58F424487616678F FOREIGN KEY (rank_id) REFERENCES com_rank (id)");
        $this->addSql("ALTER TABLE com_rankReward ADD CONSTRAINT FK_58F42448ABE136B8 FOREIGN KEY (rank_reward_type_id) REFERENCES com_rankRewardType (id)");
        $this->addSql("ALTER TABLE mbr_region ADD CONSTRAINT FK_304E11F2E80AA9BC FOREIGN KEY (iso_code_id) REFERENCES mbr_isoCode (id)");
        $this->addSql("ALTER TABLE mbr_region ADD CONSTRAINT FK_304E11F2FDD13F95 FOREIGN KEY (tax_rate_id) REFERENCES mbr_taxRate (id)");
        $this->addSql("ALTER TABLE mbr_region ADD CONSTRAINT FK_304E11F2F92F3E70 FOREIGN KEY (country_id) REFERENCES mbr_country (id)");
        $this->addSql("ALTER TABLE mbr_socialMedia ADD CONSTRAINT FK_4249EFA51221844E FOREIGN KEY (social_media_type_id) REFERENCES mbr_socialMediaType (id)");
        $this->addSql("ALTER TABLE sylius_price_wun_account_type ADD CONSTRAINT FK_B29E656FD614C7E7 FOREIGN KEY (price_id) REFERENCES sylius_product_variant_price (id)");
        $this->addSql("ALTER TABLE sylius_price_wun_account_type ADD CONSTRAINT FK_B29E656FC6798DB FOREIGN KEY (account_type_id) REFERENCES mbr_accountType (id)");
    }

    public function down(Schema $schema)
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql", "Migration can only be executed safely on 'mysql'.");
        
        $this->addSql("ALTER TABLE mbr_member DROP FOREIGN KEY FK_4FC81AFCC6798DB");
        $this->addSql("ALTER TABLE sylius_price_wun_account_type DROP FOREIGN KEY FK_B29E656FC6798DB");
        $this->addSql("ALTER TABLE mbr_addressAddressTypeLink DROP FOREIGN KEY FK_30E0CA44F5B7AF75");
        $this->addSql("ALTER TABLE mbr_addressOptinTypeLink DROP FOREIGN KEY FK_C7C8A35FF5B7AF75");
        $this->addSql("ALTER TABLE mbr_addressOptinAudit DROP FOREIGN KEY FK_F286CEC7F5B7AF75");
        $this->addSql("ALTER TABLE mbr_businessAddressLink DROP FOREIGN KEY FK_88F78A72F5B7AF75");
        $this->addSql("ALTER TABLE mbr_contactAddressLink DROP FOREIGN KEY FK_52C848E7F5B7AF75");
        $this->addSql("ALTER TABLE mbr_addressAddressTypeLink DROP FOREIGN KEY FK_30E0CA449EA97B0B");
        $this->addSql("ALTER TABLE mbr_businessAddressLink DROP FOREIGN KEY FK_88F78A72A89DB457");
        $this->addSql("ALTER TABLE mbr_businessEmailLink DROP FOREIGN KEY FK_3EC2BD2CA89DB457");
        $this->addSql("ALTER TABLE mbr_businessPhoneLink DROP FOREIGN KEY FK_D05F9DE2A89DB457");
        $this->addSql("ALTER TABLE mbr_contactBusinessLink DROP FOREIGN KEY FK_509E4031A89DB457");
        $this->addSql("ALTER TABLE mbr_contactBusinessLink DROP FOREIGN KEY FK_509E4031E7A1254A");
        $this->addSql("ALTER TABLE mbr_contactAddressLink DROP FOREIGN KEY FK_52C848E7E7A1254A");
        $this->addSql("ALTER TABLE mbr_contactEmailLink DROP FOREIGN KEY FK_410FDE15E7A1254A");
        $this->addSql("ALTER TABLE mbr_contactPhoneLink DROP FOREIGN KEY FK_AF92FEDBE7A1254A");
        $this->addSql("ALTER TABLE mbr_contactContactTypeLink DROP FOREIGN KEY FK_AA5F436BE7A1254A");
        $this->addSql("ALTER TABLE mbr_memberContactLink DROP FOREIGN KEY FK_E0A45441E7A1254A");
        $this->addSql("ALTER TABLE mbr_contactContactTypeLink DROP FOREIGN KEY FK_AA5F436B5F63AD12");
        $this->addSql("ALTER TABLE mbr_address DROP FOREIGN KEY FK_E7A40458F92F3E70");
        $this->addSql("ALTER TABLE mbr_region DROP FOREIGN KEY FK_304E11F2F92F3E70");
        $this->addSql("ALTER TABLE mbr_businessEmailLink DROP FOREIGN KEY FK_3EC2BD2CA832C1C9");
        $this->addSql("ALTER TABLE mbr_contactEmailLink DROP FOREIGN KEY FK_410FDE15A832C1C9");
        $this->addSql("ALTER TABLE mbr_emailEmailTypeLink DROP FOREIGN KEY FK_B537F65AA832C1C9");
        $this->addSql("ALTER TABLE mbr_emailOptinTypeLink DROP FOREIGN KEY FK_EC883C61A832C1C9");
        $this->addSql("ALTER TABLE mbr_emailOptinAudit DROP FOREIGN KEY FK_EA66841CA832C1C9");
        $this->addSql("ALTER TABLE mbr_emailValidate DROP FOREIGN KEY FK_B4882621A832C1C9");
        $this->addSql("ALTER TABLE mbr_memberSite DROP FOREIGN KEY FK_F1302824A832C1C9");
        $this->addSql("ALTER TABLE mbr_emailEmailTypeLink DROP FOREIGN KEY FK_B537F65A788CE45C");
        $this->addSql("ALTER TABLE mbr_memberFlagTypeLink DROP FOREIGN KEY FK_DA499A1134753ADC");
        $this->addSql("ALTER TABLE mbr_memberFlagAudit DROP FOREIGN KEY FK_FD4BF03C34753ADC");
        $this->addSql("ALTER TABLE mbr_country DROP FOREIGN KEY FK_B999A2BFE80AA9BC");
        $this->addSql("ALTER TABLE mbr_language DROP FOREIGN KEY FK_2B3EF1AEE80AA9BC");
        $this->addSql("ALTER TABLE mbr_region DROP FOREIGN KEY FK_304E11F2E80AA9BC");
        $this->addSql("ALTER TABLE mbr_contact DROP FOREIGN KEY FK_A6888DE182F1BAF4");
        $this->addSql("ALTER TABLE mbr_member DROP FOREIGN KEY FK_4FC81AFC9F7F6383");
        $this->addSql("ALTER TABLE mbr_memberContactLink DROP FOREIGN KEY FK_E0A454417597D3FE");
        $this->addSql("ALTER TABLE mbr_memberFlagTypeLink DROP FOREIGN KEY FK_DA499A117597D3FE");
        $this->addSql("ALTER TABLE mbr_memberFlagAudit DROP FOREIGN KEY FK_FD4BF03C7597D3FE");
        $this->addSql("ALTER TABLE mbr_memberLoginAudit DROP FOREIGN KEY FK_AF4DD5197597D3FE");
        $this->addSql("ALTER TABLE mbr_memberMeta DROP FOREIGN KEY FK_4F8135F57597D3FE");
        $this->addSql("ALTER TABLE mbr_memberSite DROP FOREIGN KEY FK_F13028247597D3FE");
        $this->addSql("ALTER TABLE mbr_memberStatusTypeAudit DROP FOREIGN KEY FK_DC6511BF7597D3FE");
        $this->addSql("ALTER TABLE mbr_memberSiteSocialMediaLink DROP FOREIGN KEY FK_1EB442FE4949A1D2");
        $this->addSql("ALTER TABLE mbr_memberMeta DROP FOREIGN KEY FK_4F8135F58C379371");
        $this->addSql("ALTER TABLE mbr_addressOptinTypeLink DROP FOREIGN KEY FK_C7C8A35F21332E67");
        $this->addSql("ALTER TABLE mbr_addressOptinAudit DROP FOREIGN KEY FK_F286CEC721332E67");
        $this->addSql("ALTER TABLE mbr_emailOptinTypeLink DROP FOREIGN KEY FK_EC883C6121332E67");
        $this->addSql("ALTER TABLE mbr_emailOptinAudit DROP FOREIGN KEY FK_EA66841C21332E67");
        $this->addSql("ALTER TABLE mbr_phoneOptinTypeLink DROP FOREIGN KEY FK_C7AAEBE321332E67");
        $this->addSql("ALTER TABLE mbr_phoneOptinAudit DROP FOREIGN KEY FK_EC13100F21332E67");
        $this->addSql("ALTER TABLE mbr_businessPhoneLink DROP FOREIGN KEY FK_D05F9DE23B7323CB");
        $this->addSql("ALTER TABLE mbr_contactPhoneLink DROP FOREIGN KEY FK_AF92FEDB3B7323CB");
        $this->addSql("ALTER TABLE mbr_memberSite DROP FOREIGN KEY FK_F13028243B7323CB");
        $this->addSql("ALTER TABLE mbr_phonePhoneTypeLink DROP FOREIGN KEY FK_B397C5253B7323CB");
        $this->addSql("ALTER TABLE mbr_phoneOptinTypeLink DROP FOREIGN KEY FK_C7AAEBE33B7323CB");
        $this->addSql("ALTER TABLE mbr_phoneOptinAudit DROP FOREIGN KEY FK_EC13100F3B7323CB");
        $this->addSql("ALTER TABLE mbr_phonePhoneTypeLink DROP FOREIGN KEY FK_B397C525550E00A1");
        $this->addSql("ALTER TABLE mbr_member DROP FOREIGN KEY FK_4FC81AFCD3FFF3B9");
        $this->addSql("ALTER TABLE com_rank DROP FOREIGN KEY FK_E1AC375A727ACA70");
        $this->addSql("ALTER TABLE com_rankMeta DROP FOREIGN KEY FK_27EB86D37616678F");
        $this->addSql("ALTER TABLE com_rankRequirement DROP FOREIGN KEY FK_7792617616678F");
        $this->addSql("ALTER TABLE com_rankReward DROP FOREIGN KEY FK_58F424487616678F");
        $this->addSql("ALTER TABLE com_rankRequirement DROP FOREIGN KEY FK_779261180EBDEC");
        $this->addSql("ALTER TABLE com_rankReward DROP FOREIGN KEY FK_58F42448ABE136B8");
        $this->addSql("ALTER TABLE mbr_address DROP FOREIGN KEY FK_E7A4045898260155");
        $this->addSql("ALTER TABLE mbr_memberSiteSocialMediaLink DROP FOREIGN KEY FK_1EB442FE64AE4959");
        $this->addSql("ALTER TABLE mbr_socialMedia DROP FOREIGN KEY FK_4249EFA51221844E");
        $this->addSql("ALTER TABLE mbr_member DROP FOREIGN KEY FK_4FC81AFCCD9CFB16");
        $this->addSql("ALTER TABLE mbr_memberStatusTypeAudit DROP FOREIGN KEY FK_DC6511BFCD9CFB16");
        $this->addSql("ALTER TABLE mbr_country DROP FOREIGN KEY FK_B999A2BFFDD13F95");
        $this->addSql("ALTER TABLE mbr_region DROP FOREIGN KEY FK_304E11F2FDD13F95");
        $this->addSql("DROP TABLE mbr_accountType");
        $this->addSql("DROP TABLE mbr_address");
        $this->addSql("DROP TABLE mbr_addressAddressTypeLink");
        $this->addSql("DROP TABLE mbr_addressOptinTypeLink");
        $this->addSql("DROP TABLE mbr_addressOptinAudit");
        $this->addSql("DROP TABLE mbr_addressType");
        $this->addSql("DROP TABLE mbr_business");
        $this->addSql("DROP TABLE mbr_businessAddressLink");
        $this->addSql("DROP TABLE mbr_businessEmailLink");
        $this->addSql("DROP TABLE mbr_businessPhoneLink");
        $this->addSql("DROP TABLE mbr_contact");
        $this->addSql("DROP TABLE mbr_contactBusinessLink");
        $this->addSql("DROP TABLE mbr_contactAddressLink");
        $this->addSql("DROP TABLE mbr_contactEmailLink");
        $this->addSql("DROP TABLE mbr_contactPhoneLink");
        $this->addSql("DROP TABLE mbr_contactContactTypeLink");
        $this->addSql("DROP TABLE mbr_contactType");
        $this->addSql("DROP TABLE mbr_country");
        $this->addSql("DROP TABLE mbr_email");
        $this->addSql("DROP TABLE mbr_emailEmailTypeLink");
        $this->addSql("DROP TABLE mbr_emailOptinTypeLink");
        $this->addSql("DROP TABLE mbr_emailOptinAudit");
        $this->addSql("DROP TABLE mbr_emailType");
        $this->addSql("DROP TABLE mbr_emailValidate");
        $this->addSql("DROP TABLE mbr_flagType");
        $this->addSql("DROP TABLE mbr_isoCode");
        $this->addSql("DROP TABLE mbr_language");
        $this->addSql("DROP TABLE mbr_member");
        $this->addSql("DROP TABLE mbr_memberContactLink");
        $this->addSql("DROP TABLE mbr_memberFlagTypeLink");
        $this->addSql("DROP TABLE mbr_memberFlagAudit");
        $this->addSql("DROP TABLE mbr_memberLoginAudit");
        $this->addSql("DROP TABLE mbr_memberMeta");
        $this->addSql("DROP TABLE mbr_memberSite");
        $this->addSql("DROP TABLE mbr_memberSiteSocialMediaLink");
        $this->addSql("DROP TABLE mbr_memberStatusTypeAudit");
        $this->addSql("DROP TABLE mbr_metaType");
        $this->addSql("DROP TABLE mbr_optinType");
        $this->addSql("DROP TABLE mbr_phone");
        $this->addSql("DROP TABLE mbr_phonePhoneTypeLink");
        $this->addSql("DROP TABLE mbr_phoneOptinTypeLink");
        $this->addSql("DROP TABLE mbr_phoneOptinAudit");
        $this->addSql("DROP TABLE mbr_phoneType");
        $this->addSql("DROP TABLE com_rank");
        $this->addSql("DROP TABLE com_rankMeta");
        $this->addSql("DROP TABLE com_rankRequirement");
        $this->addSql("DROP TABLE com_rankRequirementType");
        $this->addSql("DROP TABLE com_rankReward");
        $this->addSql("DROP TABLE com_rankRewardType");
        $this->addSql("DROP TABLE mbr_region");
        $this->addSql("DROP TABLE mbr_socialMedia");
        $this->addSql("DROP TABLE mbr_socialMediaType");
        $this->addSql("DROP TABLE mbr_statusType");
        $this->addSql("DROP TABLE mbr_taxRate");
        $this->addSql("DROP TABLE sylius_price_wun_account_type");
    }
}
