# This file is part of the Sylius package.
# (c) Paweł Jędrzejewski

sylius_backend_interval_index:
    pattern: /
    methods: [GET]
    defaults:
        _controller: sylius.controller.interval:indexAction
        _sylius:
            template: SyliusWebBundle:Backend/Interval:index.html.twig
            sortable: true
            sorting:
                name: desc

sylius_backend_interval_create:
    pattern: /new
    methods: [GET, POST]
    defaults:
        _controller: sylius.controller.interval:createAction
        _sylius:
            template: SyliusWebBundle:Backend/Interval:create.html.twig
            redirect: sylius_backend_interval_show

sylius_backend_interval_update:
    pattern: /{id}/edit
    methods: [GET, PUT, POST]
    defaults:
        _controller: sylius.controller.interval:updateAction
        _sylius:
            template: SyliusWebBundle:Backend/Interval:update.html.twig
            redirect: sylius_backend_interval_show

sylius_backend_interval_delete:
    pattern: /{id}
    methods: [DELETE]
    defaults:
        _controller: sylius.controller.interval:deleteAction
        _sylius:
            template: SyliusWebBundle:Backend/Misc:delete.html.twig
            redirect: sylius_backend_interval_index

sylius_backend_interval_history:
    pattern: /{id}/history
    methods: [GET]
    defaults:
        _controller: sylius.controller.interval:historyAction
        _sylius:
            template: SyliusWebBundle:Backend/Interval:history.html.twig
            method: findForDetailsPage
            arguments: [$id]

sylius_backend_interval_show:
    pattern: /{id}
    methods: [GET]
    defaults:
        _controller: sylius.controller.interval:showAction
        _sylius:
            template: SyliusWebBundle:Backend/Interval:show.html.twig
            method: findForDetailsPage
            arguments: [$id]
